### ISSUE TITLE
need "Hello World" example

### ISSUE THREAD

**Issue by NodeGuy** [wallabyjs/wallabify#1]
This looks very promising but I can't get it to work.  I'm new to Wallaby, Browserify, and WebStorm so that may be the problem.

Would you please add a simple working example so I can see how to wire things up?

I can't figure out how to reference the top-level module exports from my Jasmine spec file.

I've got this in my `helloworld.js` file:

```
module.exports = {
  getItem: getItem,
  setItem: setItem
};
```

I want to reference `HelloWorld.getItem` in my Jasmine test but `HelloWorld` is undefined.  In my web app I normally use the `--standalone HelloWorld` option to Browserify.  I tried adding `require('helloworld.js')` to my spec file but that didn't work either.

**Comment by ArtemGovorov** [comment]
I have created a simple example - https://github.com/wallabyjs/wallaby-browserify-sample
Just run `npm install` and you are ready to go.

**Comment by NodeGuy** [comment]
Thank you!
