### ISSUE TITLE
Coffee extensions not found, disable compilers?

### ISSUE THREAD

**Issue by maxparm** [wallabyjs/wallabify#7]
I'm giving another try to wallaby, I could not get it to work the last time:  https://github.com/wallabyjs/wallabify/issues/4

So my wallaby configuration file is:

``` js
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
    debug: true,
}, function (b) {
    return b.transform(require('coffeeify'));
});

module.exports = function (w) {
    return {
        files: [{
            pattern: 'static/components/jquery/jquery.js',
            load: false,
            instrumented: false
        }, {
            pattern: 'static/js/apps/stream/models/wallaby*',
            load: false, // will not be loaded
            instrument: true // will not be executed
        }],
        tests: [{
            pattern: 'static/js/apps/stream/models/tests/wallaby.coffee',
            load: false
        }],
        debug: true,
        testFramework: 'mocha',
        compilers: {},
        postprocessor: wallabyPostprocessor,
        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

My test file is:

``` coffee
Wallaby = require('../wallaby.coffee')
Wallaby2 = require('../wallaby2.js')
assert = require('chai').assert

describe('Wallaby', ->
    model = null

    descrIbe('wallaby #hello', ->
        It('should Return Hello', ->
            Assert.equal(wallaby.hello(), 'hello')
        )
    )
    describe('Wallaby2 #hello', ->
        it('should return hello', ->
            assert.equal(Wallaby2.hello(), 'hello')
        )
    )
)
```

When I don't require a `.coffee` in my test it works but when I require one I get the following error: `wallaby:project Error: Cannot find module '../wallaby.coffee'`. This is due to the fact that the compiler is transforming `wallaby.coffee` to `wallaby.js` in the instrumented files.

If I remove the extension `Wallaby = require('../wallaby')` in my test file, it half works but then it does not give me the feedback in my IDE on the `wallaby.coffee` file...

Is there a way to deactivate the compilers? so it would send the *.coffee to the instrumented files?

Thanks for the help!

**Comment by ArtemGovorov** [comment]
First of all, as I have mentioned in the referenced issue, with CoffeeScript, you need to use a CoffeeScript compiler instead of the transform with wallaby.js, because with the transform in the postprocessor, it is too late for wallaby to instrument the resulting JavaScript. There's no way to deactivate the compilers and you don't need to do it.

Wallaby compiler is indeed transforming x.coffee to x.js by default. If you'd like to stop it, you may just pass the `noFileRename` option to the compiler.

I have created the working sample reproducing your file structure here https://github.com/wallabyjs/wallabify-4.

So your wallaby config may look like

``` javascript
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
  debug: true
});

module.exports = function (w) {
  return {
    files: [{
      pattern: 'static/components/jquery/jquery.js',
      load: false,
      instrumented: false
    }, {
      pattern: 'static/js/apps/stream/models/wallaby*',
      load: false, // will not be loaded
      instrument: true // will not be executed
    }],
    tests: [{
      pattern: 'static/js/apps/stream/models/tests/wallaby.coffee',
      load: false
    }],
    debug: true,
    testFramework: 'mocha',
    compilers: {
      '**/*.coffee': w.compilers.coffeeScript({noFileRename: true})
    },
    postprocessor: wallabyPostprocessor,
    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

Let me know if it works for you.

**Comment by maxparm** [comment]
Perfect this works! Thanks again!!
