### ISSUE TITLE
Post processor fails for relative paths

### ISSUE THREAD

**Issue by nim23** [wallabyjs/wallabify#8]
Here is a link to sample repo https://github.com/nim23/wallaby-test which tries to replicate the scenario of a real life project I am working on. In [Application.spec.js](https://github.com/nim23/wallaby-test/blob/dev/src/javascript/components/Application.spec.js) as soon as I `import Application from './Application.jsx'` wallabify fails to import the relative module dependencies causing wallaby to fail.

**Comment by ArtemGovorov** [comment]
Closing a s a duplicate of https://github.com/wallabyjs/public/issues/615
